# Generated by Django 3.1.1 on 2020-10-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notesfile',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
