# Generated by Django 3.1.1 on 2020-10-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_auto_20201023_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(max_length=30, null=True, upload_to=''),
        ),
    ]
